# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_connections=200"]

volumes:
  postgres_data:
