# docker-compose.yml
version: "3.8"
services:
  supabase:
    image: supabase/postgres
    ports:
      - "54321:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data:
